import Head from "next/head";
import Header from "../components/Header";
import Layout from "../components/Layout";
import { Hero } from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Seattle Moving Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Layout />
      
    </>
  );
}
